### PR TITLE
Delay destroying window to avoid triggering a re-open

### LINKED ISSUE #18: Grab overlay keydown, and close on keyup
Apparently the overlay key unfocuses the window on keydown, then fires the event on keyup. This makes the shortcut overlay close and immediately reopen when the super key is pressed.

@danrabbit wondered if we could grab the overlay keydown (to make it not unfocus the window), then close the window on keyup. This would mean tapping the overlay key without the app open would open it, tapping it again would close it.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/55927143-grab-overlay-keydown-and-close-on-keyup?utm_campaign=plugin&utm_content=tracker%2F77500418&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F77500418&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vkareh**
By destroying the window after a small timeout, it avoids re-triggering the shortcut-overlay, as it's already open. This allows the user to close the overlay with the same shortcut that it was open (i.e. `Super_L`).

Fixes #18

### CODE REVIEW

**Comment by danrabbit** [comment]
I hate to rain on the parade because I was thinking of this solution as well, but the problem is that we lose focus on keydown and the overlay key triggers on keyup. So this only works if you tap the key very quickly. It doesn't work for longer key presses, which feels pretty non-deterministic.

I wonder if we can check on focus out if there's a key down event for super L or super R and skip closing the window in that case

**Comment by cassidyjames** [comment]
This feels gross, but if it's the most sane way, I'm fine with it. I would just want to add a comment in the code to explain why there's a timeout.

**Comment by aroman** [comment]
elementary uses X for now. I agree that the least hacky way to solve this problem is to add some special logic in gala/mutter. 

How does GNOME Shell's overlay behave if closed and reopened by pressing super twice? Does it have the same (undesirable) behavior as overlay-shortcut currently does (closing and reopening quickly) or does it behave correctly (press once to open, press again to close)?

If it does have behave correctly, how is it doing that? We should probably do that.
If it doesn't, we should probably handle this in gala, rather than in shortcut-overlay. Afterall, it's libmutter that's causing the weirdness here.

**Comment by donadigo** [comment]
* Make the window only hide when the user does Super again.
* If the WM spawns another instance of the app, close.

**Comment by vkareh** [comment]
@danrabbit - I took some inspiration from @donadigo's #50 and updated my pull request. Basically it hides the window immediately, and delays destroying it. The 500ms is long enough that a reasonably long key press won't retrigger it, while short enough that the user can re-open the overlay almost immediately.

**Comment by cassidyjames** [comment]
Implementation aside, this does seem to work reasonably well. I'll leave it up to @danrabbit and/or @donadigo to code review. My only other code critique would be to add a comment explaining why the timeout is there, so future developers will have a little more insight into the workaround.

**Comment by vkareh** [comment]
@cassidyjames - good point, I've updated my last commit

**Pull request merged**
