### PR TITLE
Chinese(Simplified) translation for "Copy an area to clipboard"

### PR DESCRIPTION
**Pull request by sauntor**

### CODE REVIEW

**Comment by tintou** [comment]
Hi there! We are using [the elementary Weblate](https://l10n.elementary.io/projects/desktop/shortcut-overlay/) to translate our software

**Comment by sauntor** [comment]
@tintou I'm from China, I think I know what chinese call something daliy, mail me if some there's something to be translating.

**Comment by sauntor** [comment]
@tintou I'm sorry, I know what you mean now, I will try it. Thanks.

**Comment by sauntor** [comment]
The `Save` button is always disabled, how can I make it enabled?
image

**Comment by 1280px** [comment]
> @tintou The `Save` button is always disabled, how can I make it enabled? (My account is `sauntor`) image

I'm probably extremely late, but if you still didn't get a permission to translate and will to contribute, you can ask for it here: https://matrix.to/#/%23elementary-contrib%3Amatrix.org

Otherwise, it would probably make sense to close the issue as completed :)

**Pull request closed without merging**
